site_name: Conia Log
copyright: © 2023 ebene fünf GmbH
nav:
  - index.md
theme:
    name: conia
repo_url: https://github.com/coniadev/log
extra:
    project: Log
plugins:
    - search
    - macros:
        module_name: docs/main
